-- DEPRECATED: use supabase_schema.sql for the current Wallet.
-- The current app stores transactions and categories as individual rows in:
--   public.wallet_transactions
--   public.wallet_categories
--
-- Run supabase_schema.sql once in Supabase SQL Editor.
-- The legacy public.wallet_data JSONB table is no longer read by the app.
