'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useWallet} from './WalletProvider';
import {monthLabel,shiftMonth} from '@/lib/wallet/calc';
import {useState} from 'react';
import ProfileMenu from '@/components/ProfileMenu';
const NAV=[['/dashboard/wallet','▦','Dashboard'],['/dashboard/wallet/transactions','↔','Transactions'],['/dashboard/wallet/transport','◉','Transport'],['/dashboard/wallet/savings','▱','Savings'],['/dashboard/wallet/debt','◌','Debt & Borrowing'],['/dashboard/wallet/charts','◒','Charts & Stats']];
export default function WalletShell({children,title='Wallet'}){const p=usePathname(),r=useRouter(),{user,saving,month,setMonth}=useWallet();const [gate,setGate]=useState(false);
 const protectedAction=fn=>user?fn():setGate(true);
 return <div className="wallet-shell"><aside className="wallet-sidebar"><Link href="/dashboard/wallet" className="wallet-brand"><span>SP</span><b>Sultan Pocket</b></Link><nav>{NAV.map(([href,ic,label])=><Link className={p===href?'active':''} key={href} href={href}><i>{ic}</i>{label}</Link>)}</nav><div className="wallet-side-foot"><Link href="/dashboard">← Main dashboard</Link>{user?<Link href={`/u/${encodeURIComponent(user.user_metadata?.username||user.email?.split('@')[0]||'user')}`}>View profile</Link>:<button onClick={()=>setGate(true)}>Guest mode · Sign in</button>}</div></aside>
 <section className="wallet-main"><header className="wallet-topbar"><div><div className="wallet-kicker">PERSONAL FINANCE</div><h1>{title}</h1></div><div className="wallet-actions"><button className="wallet-btn" onClick={()=>setMonth(shiftMonth(month,-1))}>‹</button><div className="wallet-month">{monthLabel(month)}</div><button className="wallet-btn" onClick={()=>setMonth(shiftMonth(month,1))}>›</button><button className="wallet-btn primary" onClick={()=>protectedAction(()=>window.dispatchEvent(new CustomEvent('wallet:add',{detail:'income'})))}>+ Income</button><button className="wallet-btn danger" onClick={()=>protectedAction(()=>window.dispatchEvent(new CustomEvent('wallet:add',{detail:'expense'})))}>+ Expense</button>{user&&<ProfileMenu compact />}{saving&&<span className="wallet-saving">Saving…</span>}</div></header><main className="wallet-content">{children}</main></section>{gate&&<GateModal close={()=>setGate(false)} router={r}/>}</div>}
function GateModal({close,router}){return <div className="gate-backdrop"><div className="gate-modal"><button className="gate-x" onClick={close}>×</button><div className="gate-icon">↗</div><h2>Sign in to continue</h2><p>Guests can browse Sultan Pocket, but saving, editing and personal data require an account.</p><div className="gate-buttons"><button className="wallet-btn primary" onClick={()=>router.push('/signin')}>Sign in</button><button className="wallet-btn" onClick={()=>router.push('/signup')}>Create account</button></div></div></div>}
