'use client';
import {useMemo,useState} from 'react';
import {useWallet} from './WalletProvider';
import {balances,money,stats,monthLabel} from '@/lib/wallet/calc';

function Actions({items}){const {notify,user}=useWallet();return <div className="wallet-quick-actions">{items.map(([kind,label])=><button key={kind} className="wallet-btn action-btn" onClick={()=>user?window.dispatchEvent(new CustomEvent('wallet:add',{detail:kind})):notify('Please sign in to continue.')}>{label}</button>)}</div>}
function Card({label,value,sub,accent}){return <div className="wallet-card" style={{'--accent':accent||'var(--signal)'}}><small>{label}</small><strong>{value}</strong>{sub&&<span>{sub}</span>}</div>}
function DemoNotice({gate}){return <div className="wallet-demo"><b>Guest browsing</b><span>You’re viewing an empty demo workspace. Sign in to save your own transactions.</span><button className="wallet-btn primary" onClick={gate}>Sign in</button></div>}
function useData(){const {state,user,month}=useWallet();const tx=user?state.transactions:[];return {user,tx,month,s:stats(tx,month),b:balances(tx),state};}

export function Dashboard(){return <Page title="Wallet overview"><DashboardInner/></Page>}
function DashboardInner(){const {user,s,b,tx,month}=useData();const {notify}=useWallet();const gate=()=>notify('Please sign in to continue.');return <>{!user&&<DemoNotice gate={gate}/>}<div className="wallet-grid four"><Card label="Available" value={money(b.available)} sub="Cash + online"/><Card label="Savings" value={money(b.savings)} sub="Set aside" accent="var(--success)"/><Card label="E-Transit" value={money(b.etransit)} sub="Current balance" accent="#8656C4"/><Card label="Still owed" value={money(b.owed)} sub="Borrowed & repayable" accent="var(--danger)"/></div><div className="wallet-grid two"><section className="wallet-panel"><h2>{monthLabel(month)}</h2><div className="metric-list"><div><span>Income</span><b className="positive">{money(s.income)}</b></div><div><span>Expenses</span><b className="negative">{money(s.expenses)}</b></div><div><span>Savings added</span><b>{money(s.savingsAdded)}</b></div><div><span>Transport</span><b>{money(s.transport)}</b></div></div></section><section className="wallet-panel"><h2>Recent transactions</h2><TxTable tx={tx.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6)} empty="No transactions yet."/></section></div></>}

export function Transactions(){return <Page title="Transactions"><TransactionsInner/></Page>}
function TransactionsInner(){const {user,tx}=useData();const {notify}=useWallet();const gate=()=>notify('Please sign in to continue.');return <>{!user&&<DemoNotice gate={gate}/>}<section className="wallet-panel"><div className="wallet-panel-head"><div><span className="wallet-section-kicker">LEDGER</span><h2>All transactions</h2></div><div className="wallet-panel-tools"><span>{tx.length} total</span>{user&&<button className="wallet-btn export-btn" onClick={()=>exportCSV(tx)}>↓ Export CSV</button>}</div></div><TxTable tx={tx.slice().sort((a,b)=>b.date.localeCompare(a.date))} empty="Your transaction ledger is empty."/></section></>}

function TxTable({tx,empty}){const {remove,user}=useWallet();const [confirmId,setConfirmId]=useState(null);if(!tx.length)return <div className="wallet-empty">{empty}</div>;const confirmTx=tx.find(t=>t.id===confirmId);return <><div className="wallet-table-wrap"><table className="wallet-table"><thead><tr><th>Date</th><th>Type</th><th>Details</th><th>Method</th><th>Amount</th><th>Actions</th></tr></thead><tbody>{tx.map(t=><tr key={t.id}><td>{t.date}</td><td><span className="wallet-pill">{displayType(t.type)}</span></td><td>{t.category||t.source||t.person||t.notes||'—'}</td><td>{displayMethod(t.method||t.from)}</td><td className={['income_other','stipend','borrow','savings_use'].includes(t.type)?'positive':'negative'}>{money(t.amount)}</td><td><div className="table-actions">{user&&<><button className="table-action edit" onClick={()=>window.dispatchEvent(new CustomEvent('wallet:edit',{detail:t}))}>Edit</button><button className="table-action delete" onClick={()=>setConfirmId(t.id)}>Delete</button></>}</div></td></tr>)}</tbody></table></div>{confirmId!==null&&<ConfirmDelete transaction={confirmTx} close={()=>setConfirmId(null)} confirm={async()=>{await remove(confirmId);setConfirmId(null)}}/>}</>}

function ConfirmDelete({transaction,close,confirm}){const [busy,setBusy]=useState(false);async function go(){setBusy(true);await confirm();setBusy(false)}return <div className="gate-backdrop"><div className="confirm-modal"><div className="confirm-icon">!</div><span className="wallet-modal-kicker">DELETE TRANSACTION</span><h2>Delete this transaction?</h2><p>This action cannot be undone. {transaction?.category||transaction?.source||displayType(transaction?.type||'transaction')} · {money(transaction?.amount)}</p><div className="confirm-actions"><button className="wallet-btn secondary" onClick={close} disabled={busy}>Cancel</button><button className="wallet-btn danger-fill" onClick={go} disabled={busy}>{busy?'Deleting…':'Yes, delete'}</button></div></div></div>}

function displayType(type){const map={income_other:'Income',stipend:'Monthly Stipend',expense:'Expense',transfer:'Transfer',withdraw:'Withdraw Cash',etransit_add:'E-Transit Top-up',savings_add:'Savings Added',savings_use:'Savings Used',borrow:'Borrowed Money',repay:'Repayment'};return map[type]||type}
function displayMethod(method){const map={cash:'Cash',online:'Online',etransit:'E-Transit Wallet'};return map[method]||'—'}
function exportCSV(tx){const headers=['Date','Type','Amount','Category','Source','Method','Person','Notes'];const rows=tx.map(t=>[t.date,displayType(t.type),t.amount,t.category||'',t.source||'',displayMethod(t.method||t.from),t.person||'',t.notes||'']);const csv=[headers,...rows].map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([`\ufeff${csv}`],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`sultan-pocket-transactions-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}

export function Transport(){return <Page title="Transport"><TransportInner/></Page>}
function TransportInner(){const {user,s}=useData();const {notify}=useWallet();return <>{!user&&<DemoNotice gate={()=>notify('Please sign in to continue.')}/>}<Actions items={[["etransit_add","＋ Add to E-Transit"],["expense","＋ Add Transport Expense"]]}/><div className="wallet-grid four"><Card label="Transport this month" value={money(s.transport)}/><Card label="E-Transit used" value={money(s.tx.filter(t=>t.type==='expense'&&t.method==='etransit').reduce((a,t)=>a+t.amount,0))} accent="#8656C4"/><Card label="Other transport" value={money(s.tx.filter(t=>t.type==='expense'&&t.category==='Transport'&&t.method!=='etransit').reduce((a,t)=>a+t.amount,0))}/><Card label="Top-ups" value={money(s.tx.filter(t=>t.type==='etransit_add').reduce((a,t)=>a+t.amount,0))} accent="var(--success)"/></div><section className="wallet-panel"><h2>Transport activity</h2><TxTable tx={s.tx.filter(t=>t.category==='Transport'||t.type==='etransit_add')} empty="No transport activity this month."/></section></>}

export function Savings(){return <Page title="Savings"><SavingsInner/></Page>}
function SavingsInner(){const {user,s,b}=useData();const {notify}=useWallet();return <>{!user&&<DemoNotice gate={()=>notify('Please sign in to continue.')}/>}<Actions items={[["savings_add","＋ Add Savings"],["savings_use","＋ Use Savings"]]}/><div className="wallet-grid four"><Card label="Savings balance" value={money(b.savings)} accent="var(--success)"/><Card label="Added this month" value={money(s.savingsAdded)}/><Card label="Used this month" value={money(s.savingsUsed)} accent="var(--danger)"/><Card label="Available outside savings" value={money(b.available)}/></div><section className="wallet-panel"><h2>Savings activity</h2><TxTable tx={s.tx.filter(t=>t.type.startsWith('savings_'))} empty="No savings activity this month."/></section></>}

export function Debt(){return <Page title="Debt & Borrowing"><DebtInner/></Page>}
function DebtInner(){const {user,s,b}=useData();const {notify}=useWallet();return <>{!user&&<DemoNotice gate={()=>notify('Please sign in to continue.')}/>}<Actions items={[["borrow","＋ Borrow Money"],["repay","＋ Repay Money"]]}/><div className="wallet-grid three"><Card label="Still owed" value={money(b.owed)} accent="var(--danger)"/><Card label="Borrowed total" value={money(b.borrowed)}/><Card label="Repaid total" value={money(b.repaid)} accent="var(--success)"/></div><section className="wallet-panel"><h2>Borrowing & repayments</h2><TxTable tx={s.tx.filter(t=>t.type==='borrow'||t.type==='repay')} empty="No debt activity this month."/></section></>}

export function Charts(){return <Page title="Charts & statistics"><ChartsInner/></Page>}
function ChartsInner(){const {user,s,month}=useData();const {notify}=useWallet();const cats=Object.entries(s.byCategory);const max=Math.max(1,...cats.map(([,v])=>v));return <>{!user&&<DemoNotice gate={()=>notify('Please sign in to continue.')}/>}<div className="wallet-grid two"><section className="wallet-panel"><h2>Expenses by category</h2>{cats.length?cats.map(([k,v])=><div className="bar" key={k}><div><span>{k}</span><b>{money(v)}</b></div><i><em style={{width:`${(v/max)*100}%`}}/></i></div>):<div className="wallet-empty">No expense data for this month.</div>}</section><section className="wallet-panel"><h2>Monthly snapshot</h2><div className="metric-list"><div><span>Income</span><b className="positive">{money(s.income)}</b></div><div><span>Expenses</span><b className="negative">{money(s.expenses)}</b></div><div><span>Transport</span><b>{money(s.transport)}</b></div><div><span>Savings added</span><b>{money(s.savingsAdded)}</b></div></div></section></div></>}
function Page({title,children}){return <div className="wallet-page"><div className="wallet-page-title"><div><span>WALLET</span><h2>{title}</h2></div></div>{children}</div>}
