'use client';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '@/lib/supabaseClient';
const suggestions=['What is Sultan Pocket?','How much cash do I have?','What did I spend this month?','What bills are coming up?'];
const POS_KEY='sultan-pocket-ai-position'; const HIDDEN_KEY='sultan-pocket-ai-hidden';
export default function Assistant(){
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[pending,setPending]=useState(null),[error,setError]=useState('');
 const [hidden,setHidden]=useState(false); const [pos,setPos]=useState(null); const drag=useRef(null); const moved=useRef(false);
 useEffect(()=>{const onOpen=e=>{setHidden(false);localStorage.removeItem(HIDDEN_KEY);setOpen(true);const prefill=e?.detail;if(typeof prefill==='string'&&prefill.trim())setInput(prefill);};window.addEventListener('sultan-pocket:assistant',onOpen);setHidden(localStorage.getItem(HIDDEN_KEY)==='1');try{const saved=JSON.parse(localStorage.getItem(POS_KEY)||'null');if(saved&&Number.isFinite(saved.x)&&Number.isFinite(saved.y))setPos(saved)}catch{} return()=>window.removeEventListener('sultan-pocket:assistant',onOpen)},[]);
 useEffect(()=>{const move=e=>{if(!drag.current)return;moved.current=true;const x=Math.max(8,Math.min(window.innerWidth-56,e.clientX-28));const y=Math.max(70,Math.min(window.innerHeight-74,e.clientY-28));const next={x,y};setPos(next);localStorage.setItem(POS_KEY,JSON.stringify(next));};const up=()=>{if(drag.current)drag.current=null};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[pos]);
 async function send(text=input){const value=String(text||'').trim();if(!value||busy)return;setInput('');setError('');const next=[...messages,{role:'user',content:value}];setMessages(next);setBusy(true);try{const {data:{session}}=await supabase.auth.getSession();const res=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json',...(session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{})},body:JSON.stringify({messages:next,page:window.location.pathname})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Assistant request failed.');if(data.pendingAction)setPending(data.pendingAction);if(data.reply)setMessages(m=>[...m,{role:'assistant',content:data.reply}]);}catch(e){setError(e.message||'Something went wrong.')}finally{setBusy(false)}}
 async function confirm(){if(!pending||busy)return;setBusy(true);setError('');try{const {data:{session}}=await supabase.auth.getSession();const res=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json',...(session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{})},body:JSON.stringify({approveAction:pending})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not complete the action.');setMessages(m=>[...m,{role:'assistant',content:data.reply||'Done.'}]);setPending(null)}catch(e){setError(e.message||'Something went wrong.')}finally{setBusy(false)}}
 function hide(){setHidden(true);localStorage.setItem(HIDDEN_KEY,'1')}
 function restore(){setHidden(false);localStorage.removeItem(HIDDEN_KEY)}
 return <>{!hidden?<button type="button" aria-label="Open Sultan Pocket AI Assistant" className="sultan-pocket-ai-launcher" style={pos?{left:pos.x,top:pos.y,right:'auto',bottom:'auto'}:undefined} title="Drag to move • double-click to hide" onPointerDown={e=>{moved.current=false;drag.current={};e.currentTarget.setPointerCapture?.(e.pointerId)}} onClick={()=>{if(!moved.current)setOpen(true)}} onDoubleClick={hide}>✦</button>:<button type="button" className="sultan-pocket-ai-restore" onClick={restore} aria-label="Restore AI Assistant">✦</button>}
 {open&&<div className="sultan-pocket-ai-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="sultan-pocket-ai-panel"><header><div><div className="sultan-pocket-ai-kicker">SULTAN POCKET AI</div><strong>Assistant</strong></div><button onClick={()=>setOpen(false)} aria-label="Close">×</button></header><div className="sultan-pocket-ai-messages">{!messages.length?<><div className="sultan-pocket-ai-intro">Ask me anything about Sultan Pocket, your account, money, budgets, goals, bills, transactions, or how the site works.</div><div className="sultan-pocket-ai-suggestions">{suggestions.map(s=><button key={s} onClick={()=>send(s)}>{s}</button>)}</div></>:messages.map((m,i)=><div key={i} className={`sultan-pocket-ai-message ${m.role}`}>{m.content}</div>)}{busy&&<div className="sultan-pocket-ai-thinking">Thinking…</div>}{pending&&<div className="sultan-pocket-ai-confirm"><strong>Confirmation needed</strong><p>{pending.description||'Confirm this change to your Sultan Pocket data?'}</p><div><button onClick={confirm} disabled={busy}>Confirm</button><button onClick={()=>setPending(null)} disabled={busy}>Cancel</button></div></div>}{error&&<div className="sultan-pocket-ai-error">{error}</div>}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask anything…" disabled={busy}/><button disabled={busy||!input.trim()}>Send</button></form></section></div>}</>;
}
