'use client';
import {useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {useAuth} from '@/components/AuthProvider';
import {supabase} from '@/lib/supabaseClient';

export default function ProfilePage(){
 const {username}=useParams();const {user,loading}=useAuth();const router=useRouter();
 const [allowed,setAllowed]=useState(false),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [form,setForm]=useState({full_name:'',username:'',bio:'',avatar_url:'',currency:'PKR',date_format:'DD/MM/YYYY'});
 const [newPassword,setNewPassword]=useState('');
 useEffect(()=>{if(!loading){const own=(user?.user_metadata?.username||'').toLowerCase()===String(username).toLowerCase();if(!own)router.replace('/signin?next='+encodeURIComponent('/u/'+username));else{setAllowed(true);const m=user.user_metadata||{};setForm({full_name:m.full_name||'',username:m.username||username,bio:m.bio||'',avatar_url:m.avatar_url||'',currency:m.currency||'PKR',date_format:m.date_format||'DD/MM/YYYY'})}}},[loading,user,username,router]);
 if(loading||!allowed)return <main style={{padding:60,textAlign:'center',color:'var(--text-faint)'}}>Loading…</main>;
 const meta=user.user_metadata||{};const initial=String(form.full_name||form.username||'U').charAt(0).toUpperCase();
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(){setBusy(true);setError('');setNotice('');const nextUsername=form.username.trim();if(!/^[a-zA-Z0-9_.]{3,20}$/.test(nextUsername)){setError('Username should be 3-20 characters using letters, numbers, _ or .');setBusy(false);return}if(nextUsername.toLowerCase()!==(meta.username||'').toLowerCase()){const {data: taken,error:rpcErr}=await supabase.rpc('is_username_taken',{uname:nextUsername});if(rpcErr||taken){setError(taken?'That username is already taken.':'Could not verify the username right now.');setBusy(false);return}}
 const {error:e}=await supabase.auth.updateUser({data:{full_name:form.full_name.trim(),username:nextUsername,bio:form.bio.trim(),avatar_url:form.avatar_url.trim(),currency:form.currency,date_format:form.date_format}});setBusy(false);if(e){setError(e.message);return}setNotice('Profile updated successfully.');setEditing(false);router.replace('/u/'+encodeURIComponent(nextUsername));}
 async function changePassword(){if(newPassword.length<6){setError('Password must be at least 6 characters.');return}setBusy(true);setError('');const {error:e}=await supabase.auth.updateUser({password:newPassword});setBusy(false);if(e)setError(e.message);else{setNewPassword('');setNotice('Password updated successfully.')}}
 async function signOut(){await supabase.auth.signOut();router.push('/signin')}
 return <main className="profile-page"><section className="profile-card"><div className="profile-cover"><div className="profile-large-avatar">{form.avatar_url?<img src={form.avatar_url} alt="Profile"/>:initial}</div><div><span className="profile-private">PRIVATE PROFILE</span><h1>{form.full_name||form.username}</h1><p>@{form.username}</p></div><button className="btn btn-primary profile-edit-btn" onClick={()=>{setEditing(v=>!v);setNotice('');setError('')}}>{editing?'Cancel':'Edit profile'}</button></div>
 {notice&&<div className="profile-notice success">{notice}</div>}{error&&<div className="profile-notice error">{error}</div>}
 {editing?<div className="profile-form"><div className="profile-form-grid"><div className="field"><label>Full name</label><input value={form.full_name} onChange={e=>set('full_name',e.target.value)}/></div><div className="field"><label>Username</label><input value={form.username} onChange={e=>set('username',e.target.value)}/></div><div className="field profile-full"><label>Profile picture URL</label><input value={form.avatar_url} onChange={e=>set('avatar_url',e.target.value)} placeholder="https://…"/></div><div className="field profile-full"><label>Bio</label><textarea value={form.bio} onChange={e=>set('bio',e.target.value)} placeholder="Tell us a little about yourself"/></div><div className="field"><label>Currency</label><select value={form.currency} onChange={e=>set('currency',e.target.value)}><option>PKR</option><option>USD</option><option>GBP</option><option>EUR</option></select></div><div className="field"><label>Date format</label><select value={form.date_format} onChange={e=>set('date_format',e.target.value)}><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></div></div><div className="profile-form-actions"><button className="btn btn-primary" onClick={save} disabled={busy}>{busy?'Saving…':'Save changes'}</button></div></div>:<div className="profile-sections"><section><h2>Personal information</h2><div className="profile-detail-grid"><Detail label="Full name" value={form.full_name||'Not set'}/><Detail label="Username" value={'@'+form.username}/><Detail label="Email" value={user.email}/><Detail label="Bio" value={form.bio||'No bio added.'}/></div></section><section><h2>Wallet preferences</h2><div className="profile-detail-grid"><Detail label="Currency" value={form.currency}/><Detail label="Date format" value={form.date_format}/><Detail label="Wallet" value="Personal finance"/><Detail label="Profile visibility" value="Private"/></div></section><section><h2>Account & security</h2><div className="password-row"><input type="password" placeholder="New password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><button className="btn" onClick={changePassword} disabled={busy}>Change password</button><button className="btn profile-signout-btn" onClick={signOut}>Sign out</button></div><p className="profile-help">Your account is private. Only you can access this profile page.</p></section></div>}
 </section></main>
}
function Detail({label,value}){return <div className="profile-detail"><span>{label}</span><strong>{value}</strong></div>}
